import {
  GuideCode,
  GuideNote,
  GuidePage,
  GuideSection,
} from '../../../layouts/GuidePage'

export function ThemeDarkModePage() {
  return (
    <GuidePage
      title='Dark mode'
      description={
        <>
          The library is dark-first. No provider is required to use dark mode —
          import the stylesheet and the default is dark. Light mode is opt-in
          via the <code>data-appearance</code> attribute.
        </>
      }>
      <GuideSection title='How it works'>
        <p className='m-0'>
          Token values are defined under{' '}
          <code>data-appearance=&quot;dark&quot;</code> (the default) and
          overridden under <code>data-appearance=&quot;light&quot;</code>. There
          is no separate light stylesheet — a single attribute flip redefines
          all tokens.
        </p>
        <GuideCode>{`/* Dark is the default — no attribute needed */
import '@caindev/ui/styles.css'

/* Opt into light mode */
document.documentElement.setAttribute('data-appearance', 'light')

/* Or use Theme */
<Theme appearance="light">...</Theme>`}</GuideCode>
      </GuideSection>

      <GuideSection title='System preference'>
        <p className='m-0'>
          Pass <code>appearance=&quot;system&quot;</code> to{' '}
          <code>&lt;Theme&gt;</code> to follow the OS preference. The resolved
          value is always <code>&quot;dark&quot;</code> or{' '}
          <code>&quot;light&quot;</code> — read{' '}
          <code>resolvedAppearance</code> from <code>useTheme</code>, never{' '}
          <code>appearance</code>, when making appearance-dependent decisions.
        </p>
        <GuideCode>{`<Theme appearance="system">
  <App />
</Theme>

// Read the resolved value
const { resolvedAppearance } = useTheme()
// resolvedAppearance is always "dark" | "light"`}</GuideCode>
      </GuideSection>

      <GuideSection title='FOUC prevention'>
        <p className='m-0'>
          Without intervention, the browser renders a frame before React mounts
          and attributes are applied. <code>ThemeScript</code> prevents this by
          setting <code>data-*</code> attributes synchronously before first
          paint.
        </p>
        <GuideCode>{`<!-- index.html — place before your stylesheet link -->
<script>
  // generated by generateThemeScript()
</script>
<link rel="stylesheet" href="/assets/index.css" />

// Or in React (e.g. Remix, Next.js _document):
import { ThemeScript } from '@caindev/ui'
<head>
  <ThemeScript appearance="dark" accent="violet" radius="md" />
  <link rel="stylesheet" href="..." />
</head>`}</GuideCode>
        <GuideNote>
          <p className='m-0'>
            <code>ThemeScript</code> reads localStorage using the same{' '}
            <code>storageKey</code> as <code>&lt;Theme&gt;</code> (default{' '}
            <code>&quot;caindev-ui-theme&quot;</code>). Pass matching{' '}
            <code>storageKey</code> to both if you customise it.
          </p>
        </GuideNote>
      </GuideSection>

      <GuideSection title='Subtree overrides'>
        <p className='m-0'>
          Apply <code>data-appearance</code> to any element (not just{' '}
          <code>documentElement</code>) to create a scoped light or dark
          region. Useful for previews, embedded panels, or side-by-side
          comparisons.
        </p>
        <GuideCode>{`<section data-appearance="light" data-accent="violet">
  <PreviewPanel />
</section>`}</GuideCode>
        <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap', marginTop: '4px' }}>
          {(['dark', 'light'] as const).map((appearance) => (
            <div key={appearance} data-appearance={appearance} style={{
              flex: '1 1 200px',
              padding: '16px',
              borderRadius: 'var(--radius-md)',
              background: 'var(--color-background-elevated)',
              border: '1px solid var(--color-border)',
              display: 'flex', flexDirection: 'column', gap: '10px',
            }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontSize: '0.8125rem', fontWeight: 600, color: 'var(--color-foreground)' }}>
                  {appearance}
                </span>
                <div style={{
                  padding: '2px 8px', borderRadius: 'var(--radius-sm)',
                  background: 'var(--color-accent)', fontSize: '0.6875rem',
                  color: 'var(--color-accent-foreground)', fontWeight: 600,
                }}>
                  accent
                </div>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                <div style={{ height: '8px', borderRadius: '4px', background: 'var(--color-foreground)', opacity: 0.9, width: '70%' }} />
                <div style={{ height: '8px', borderRadius: '4px', background: 'var(--color-foreground-muted)', opacity: 0.7, width: '90%' }} />
                <div style={{ height: '8px', borderRadius: '4px', background: 'var(--color-foreground-subtle)', opacity: 0.5, width: '50%' }} />
              </div>
              <div style={{
                padding: '6px 10px', borderRadius: 'var(--radius-sm)',
                border: '1px solid var(--color-border)',
                background: 'var(--color-surface-control)',
                fontSize: '0.75rem', color: 'var(--color-foreground-muted)',
              }}>
                Input surface
              </div>
            </div>
          ))}
        </div>
        <GuideNote>
          <p className='m-0'>
            Portaled content (Dialog, Drawer, Menu, Tooltip, Toast, Select,
            Combobox, CommandPalette) renders into <code>document.body</code>.
            It reads attributes from <code>documentElement</code>, not from a
            scoped ancestor. For portaled components, set attributes on{' '}
            <code>documentElement</code>.
          </p>
        </GuideNote>
      </GuideSection>
    </GuidePage>
  )
}
